### ISSUE TITLE
Load issue when sharing

### ISSUE THREAD

**Issue by mboskin** [covid-alert-ny/covid-green-app#95] opened 2020-08-27 00:27 UTC
August 26 4:23 EST Android  LG K40
![Screenshot-162331_3](https://user-images.githubusercontent.com/70291664/91369724-82b4df80-e7da-11ea-936d-231a57a2fd87.png)

Francisco Torrales

Loading Issue when attempting to select share option in upper right corner when attempting to share graph for Cayuga County and also during same time everyone was hung up in the app.
--

**Comment by AlanSl** [comment] 2020-08-27 13:13
I can't replicate this, this seems to work fine for me on Android, and from Slack I believe there was some discussion of connection issues which I believe was related to API work ongoing at this time.

Can you please try to replicate this again and if you can give the exact events that caused it? Thanks

**Comment by davidjharding** [comment] 2020-08-27 14:22
I am unable to reproduce this. The sharing sheet comes up reliably for me as well as the data/stats charts. I am closing this.

**Closed as completed by davidjharding** 2020-08-27 14:22 UTC
Labels: bug

**Comment by mboskin** [comment] 2020-08-27 20:35
I have updated the Issues list in Teams and asked them to retest

Thanks


www.nystec.com<http://www.nystec.com/>

**Comment by mboskin** [comment] 2020-08-27 20:38
I have marked it to be retested.

_____________________

www.nystec.com<http://www.nystec.com/>
