### ISSUE TITLE
App Icon update

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#484] opened 2020-09-21 07:21 UTC
@floridemai Let me know if I missed any asset please.
[App Icon.zip](https://github.com/project-vagabond/covid-green-app/files/5253895/App.Icon.zip)

**Comment by AlanSl** [comment] 2020-09-28 11:03
These went in to build 47. @mattobee can you verify that all is well in the builds available in the app stores and close this issue if it is.

**Comment by mattobee** [comment] 2020-09-28 13:25
@AlanSl This looks as I'd expect on iOS (I looked at build 48), but Android seems to be showing the square icon instead of the round icon. I can see that Antoine did supply a round icon in the set, so I wonder if `android:roundIcon` is set correctly in the manifest?

**Comment by AlanSl** [comment] 2020-09-30 15:23
@mattobee Can you post a lower priority issue with the details of what device and Android version you're seeing that on? Alex saw something similar but I'm only seeing the round icon in cases where round icon is used (simulated Pixel 2 on Android 10):

![image](https://user-images.githubusercontent.com/29628323/94705759-504a5500-0339-11eb-8a14-3a0bab35593c.png)

**Comment by AlanSl** [comment] 2020-09-30 15:25
@mattobee  / @helloantoine Can we close this critical issue? Then we'll follow up the round icons question on its own issue

**Comment by mattobee** [comment] 2020-09-30 15:30
Closing based on the assumption that the transient issue with the square icon appearing instead of the round icon is unrelated to the work associated with this task. Will raise it separately if we're able to reproduce it.

**Closed as completed by mattobee** 2020-09-30 15:30 UTC
Labels: Critical
