### ISSUE TITLE
Content translations - v3

### ISSUE THREAD

**Issue by floridemai** [covid-alert-ny/covid-green-app#319] opened 2020-09-04 10:52 UTC

**Comment by fahd-arshad** [comment] 2020-09-08 15:27
Calling this medium assuming that any fixes from translators validating the language as shown in the app on iOS and Android will be taken care of here.

**Comment by kevin-sheldon** [comment] 2020-09-09 13:26
I conducted my own review since we are still trying to get translators access to app. Found a number of items that need to be addressed. For the items requiring translation, can you please send an updated spreadsheet so I can get it over to the translators ASAP?
[Translation Issues_round 3.docx](https://github.com/project-vagabond/covid-green-app/files/5195434/Translation.Issues_round.3.docx)

**Comment by floridemai** [comment] 2020-09-09 14:10
@kevin-sheldon @fahd-arshad I did the following: looked back at the translations file just after we received and applied v2 and compared it with the current version. All of the differences need to be translated, so I'm attaching the file here.
❗ ❗ Very important: Lots of entries have already translation for the other languages, but those need to be verified. There were a bunch of small changes like uppercasing a letter or adding a single word etc. In the same time there might be a couple of entries that might have already been translated but it's very hard for me to be sure so I just included them.

@kevin-sheldon I'll address the above findings when I applied the v3 of the translations. Also note that Privacy Policy is not part of the app, but it's stored in the database cc @segfault 

Transaltions v3: [covid-alert-ny-translations-v3-original.xlsx](https://github.com/project-vagabond/covid-green-app/files/5195687/covid-alert-ny-translations-v3-original.xlsx)

**Comment by fahd-arshad** [comment] 2020-09-09 14:39
@floridemai what do we need to do about the in-app privacy policy translation? I know that data comes from the server...

**Comment by kevin-sheldon** [comment] 2020-09-14 13:23
@floridemai Can we add the associated line(s) for the new "Submit Feedback" feature?

**Comment by kevin-sheldon** [comment] 2020-09-14 16:11
@helloantoine can you please open up the attached word doc and look at the last image? Transliterations need to be removed for just that one language to be consistent with others.

**Comment by kevin-sheldon** [comment] 2020-09-14 16:11
![image](https://user-images.githubusercontent.com/69158966/93110536-76a69a00-f683-11ea-8cc9-c9cfc6fa0719.png)

**Comment by kevin-sheldon** [comment] 2020-09-14 16:12
![image](https://user-images.githubusercontent.com/69158966/93110590-89b96a00-f683-11ea-8acf-330927ad5655.png)

**Comment by AlanSl** [comment] 2020-09-15 14:56
@kevin-sheldon Removing English transliterations from Bengali is done in https://github.com/project-vagabond/covid-green-app/pull/436 and should be in the next build.

I'm putting together a new spreadsheet of recent English copy changes for translators.

**Comment by AlanSl** [comment] 2020-09-15 18:49
@kevin-sheldon Here is the new spreadsheet for the translators. As Paul said above, many entries already have translations but they need to be re-checked - some are only capitisation changes, some are very subtle changes in wording, some are significant changes in meaning.

It might also be worth mentioning that there are a few items in these that should not be translated because they are read as code by the app:
  - Text inside double curly brackets, like `{{county}}` or `{{page}}`, should not be changed
  - The round parenthesis part of link blocks like `[01-2345-6789](tel:0123456789)` or `[Translatable link title](http://example.com)` where round parenthesis immediately follow square brackets. Text inside the square brackets `[` `]` can be translated but the parenthesis immediately after the square brackets and their contents should not be changed. For example they have been correctly replacing other parenthesis characters in text with their Chinese equivalents but these specific parenthesis immediately following square brackets, and any `tel:` text inside, should stay unchanged.
  - Each `\n` in the spreadsheet is turned into one line break, so these should be unchanged, and it's okay for there to be no space between it and the start of the next word

It's not a major problem if they mistakenly change some of these, these are things we know to check for and can fix our side, but it'll save some time.

**[covid-alert-ny-translations-v3-200915.xlsx](https://github.com/project-vagabond/covid-green-app/files/5227120/covid-alert-ny-translations-v3-200915.xlsx)**

**Comment by kevin-sheldon** [comment] 2020-09-16 13:57
@AlanSl  Spreadsheet sent over to translators.

**Comment by AlanSl** [comment] 2020-09-16 16:26
<strike>@kevin-sheldon Can you please upload the previous spreadsheet from the tranlators in a comment here - the one you sent to Paul two weeks ago mentioned in this comment: https://github.com/project-vagabond/covid-green-app/issues/53#issuecomment-683782153 

We need to check the encoding of some of the Korean characters. Thanks!</strike> 

Nevermind, we've fixed this

**Comment by AlanSl** [comment] 2020-09-18 17:25
@kevin-sheldon Here's the updated spreadsheet, adding today's changes:

[covid-alert-ny-translations-v3-200918.xlsx](https://github.com/project-vagabond/covid-green-app/files/5247127/covid-alert-ny-translations-v3-200918.xlsx)

And this contains only today's changes since earlier this week:

[covid-alert-ny-translations-v3-200918-changes-from-200915.xlsx](https://github.com/project-vagabond/covid-green-app/files/5247157/covid-alert-ny-translations-v3-200918-changes-from-200915.xlsx)

**Comment by kevin-sheldon** [comment] 2020-09-21 13:20
@AlanSl @floridemai Translations from V3 attached. Still awaiting V4 from translator. 
[covid-alert-ny-translations-v3-200915_6 languages.xlsx](https://github.com/project-vagabond/covid-green-app/files/5255545/covid-alert-ny-translations-v3-200915_6.languages.xlsx)

**Comment by kevin-sheldon** [comment] 2020-09-21 16:52
[covid-alert-ny-translations-v4-200918-changes-from-200915_6 languages.xlsx](https://github.com/project-vagabond/covid-green-app/files/5256855/covid-alert-ny-translations-v4-200918-changes-from-200915_6.languages.xlsx)

V4 back from translators.

**Comment by AlanSl** [comment] 2020-09-21 16:59
Great, thanks @kevin-sheldon and here's version 5 which as discussed does not include the app store content.

[covid-alert-ny-translations-v5-200921.xlsx](https://github.com/project-vagabond/covid-green-app/files/5256884/covid-alert-ny-translations-v5-200921.xlsx)

**Comment by AlanSl** [comment] 2020-09-22 13:21
@kevin-sheldon I believe you will have already been told yesterday afternoon / evening that unfortunately there were some more text tweaks added requiring translation. 

If you don't have these already, they are in this spreadsheet, and I've been told there should not be any more.  

It will be worth telling the translators that the only change in the first item is changing "public health research" to "public health researchers":

UPDATE: this version has been replaced to due legal rewording, see comment below.

<strike>**[covid-alert-ny-translations-v6-200922.xlsx](https://github.com/project-vagabond/covid-green-app/files/5261619/covid-alert-ny-translations-v6-200922.xlsx)**</strike>

**Comment by AlanSl** [comment] 2020-09-22 13:59
@kevin-sheldon Alex has just told me that the under-18s text is being changed again by Legal

**Comment by AlanSl** [comment] 2020-09-22 14:42
@kevin-sheldon This sheet replaces the first v6 sheet above and includes the revised age approval text. It can be done after v5.

**[covid-alert-ny-translations-v6-200922_2.xlsx](https://github.com/project-vagabond/covid-green-app/files/5262196/covid-alert-ny-translations-v6-200922_2.xlsx)**

**Comment by fahd-arshad** [comment] 2020-09-22 20:46
On behalf of Kevin:

[covid-alert-ny-translations-v5-200921_5 languages.xlsx](https://github.com/project-vagabond/covid-green-app/files/5263921/covid-alert-ny-translations-v5-200921_5.languages.xlsx)
This has 5 languages, not Korean yet.

**Comment by kevin-sheldon** [comment] 2020-09-22 23:03
@AlanSl added Korean as well. v5 is now fully translated. 

Just awaiting v6

[covid-alert-ny-translations-v5-200921_Korean.xlsx](https://github.com/project-vagabond/covid-green-app/files/5264445/covid-alert-ny-translations-v5-200921_Korean.xlsx)

**Comment by kevin-sheldon** [comment] 2020-09-22 23:05
v6 has been translated in Russian and Bengali.

Only outstanding translations are the v6 translations for Haitian, Korean, Chinese, and Spanish

[covid-alert-ny-translations-v6-200922_2_Russian and Bengali.xlsx](https://github.com/project-vagabond/covid-green-app/files/5264458/covid-alert-ny-translations-v6-200922_2_Russian.and.Bengali.xlsx)

Sorry this is coming in pieces. Figured I would send what we have. 

@AlanSl

**Comment by floridemai** [comment] 2020-09-23 04:58
> The attached is v6 with Spanish and Chinese.  Sorry for the multiple files – let me know if they want us to put everything together tomorrow (should be easy to do) or if it’s all the same to them.

[covid-alert-ny-translations-v6-200922_2_Chinese and Spanish.xlsx](https://github.com/project-vagabond/covid-green-app/files/5265628/covid-alert-ny-translations-v6-200922_2_Chinese.and.Spanish.xlsx)

**Comment by kevin-sheldon** [comment] 2020-09-23 13:47
v6 attached with ALL languages @AlanSl 

[covid-alert-ny-translations-v6-200922_2_ALL Languages.xlsx](https://github.com/project-vagabond/covid-green-app/files/5268545/covid-alert-ny-translations-v6-200922_2_ALL.Languages.xlsx)

**Comment by AlanSl** [comment] 2020-09-23 14:16
We believe this to now be complete:

 - Everything is in build 46 except for, in ko and ht only, the age gate text and the change from "research" to "researchers" in the health log welcome screen
 - Those remaining changes are done in https://github.com/project-vagabond/covid-green-app/issues/434 and will be in build 47 later today

**Comment by AlanSl** [comment] 2020-10-02 17:00
Confirmed done

**Closed as completed by AlanSl** 2020-10-02 17:00 UTC
Labels: Critical, translation
