### ISSUE TITLE
Device offline loading message should tell user to check their internet connection

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#450] opened 2020-09-15 17:45 UTC
App version: NY app iOS 1.0.0.40
OS: iOS 13.5.1
Device: iPhone SE
Reproducible: Always

Summary: When the device has no connection and app is loaded, the user will see a red message that says "Loading issue. We were not able to load some of the data correctly."  This message should tell the user to check their internet connection.

Steps to reproduce:
1. Take device offline (in my case I do not have phone service so I turned off WiFi)
2. Launch app and go to NY COVID Data tab

Results: 
Message reads- "Loading issue. We were not able to load some of the data correctly."

Expected: 
Message should read- "Loading issue. Please check your internet connection and try to refresh the page."

![IMG_0075](https://user-images.githubusercontent.com/69995161/93244224-3f48f380-f73e-11ea-8bf1-8c3a165b524c.PNG)
Screenshot from Antoine 
![error connectivity](https://user-images.githubusercontent.com/69995161/93244308-61427600-f73e-11ea-83e5-3f301dc67b68.png)

**Comment by helloantoine** [comment] 2020-09-16 08:56
@floridemai Can we differentiate the user connectivity issue (WiFi off) from the server connectivity issues (not responding)?

**Comment by floridemai** [comment] 2020-09-16 09:31
@helloantoine Yes. We have a PR waiting to be merge (NetInfo) that would probably fix this. I'll come back but we should be addressing this pretty easy.

**Comment by AlanSl** [comment] 2020-09-16 13:10
I don't think the planned NetInfo work would fix this, it's specific to the URL iOS uses to check that the internet is really reachable, whereas this appears to be an issue of no connection being handled as an error. I'll check the code.

**Comment by AlanSl** [comment] 2020-09-16 13:22
Yeah, there's a problem with our error handling and the issue is on Android too. I'll do a quick fix for this issue and then I think after launch this should be one of the things we tidy up because currently `connected()` just throws an error and the behaviour around catching such errors is very inconsistent.

**Comment by AlanSl** [comment] 2020-09-17 11:27
@denisedresbach This should be fixed in the next build so I'm reassigning it back to you to re-test later today when build 42 is available.

**Comment by denisedresbach** [comment] 2020-09-17 20:57
Verified in Android/iOS 1.0.0.42 new message: Connection issue. Please check your internet connection and try again.
![2020-09-17](https://user-images.githubusercontent.com/69995161/93527589-f0da5700-f8ed-11ea-9486-b3572abdc726.png)

**Comment by denisedresbach** [comment] 2020-09-17 21:11
Hello @helloantoine , Looks like this one is fixed now. I noticed the message is slightly different from the screenshot you sent. The new message is "Connection issue" and yours was "Loading issue".  Is that OK?

**Comment by helloantoine** [comment] 2020-09-18 09:39
It's fine Yes. Thanks for checking @denisedresbach .

**Closed as completed by helloantoine** 2020-09-18 09:39 UTC
