### ISSUE TITLE
County Search Overlay Broken in Spanish

### ISSUE THREAD

**Issue by ahurworth** [covid-alert-ny/covid-green-app#469] opened 2020-09-18 02:06 UTC
Repro steps:
Change language to Spanish
From NY COVID data tab - tap on county selector.  
The white overlay should not extend to the top of the screen.  
@helloantoine 

![Screenshot_20200917-215739](https://user-images.githubusercontent.com/68069959/93546901-e04bd000-f931-11ea-847a-ed58c4cbaa1f.png)

**Comment by AlanSl** [comment] 2020-09-18 09:09
I can't replicate this on iOS (@JohnAGill or @floridemai  can you try?) and I can't replicate it exactly on Android, just that on Android it can be quite juddery on loading the view, it's worse after switching languages (particularly to/from Spanish presumably because of the longer "all counties" text causing a line break) and sometimes it can show a state like the one pictured for a second or two. It also seems worse on my smallest, slowest Android testing phone.

I'll look into whether there are any rerender timing issues around the keyboard avoiding view. @ahurworth can you give more details of where you're seeing this:

- What device(s) do / don't have this
- Which version of Android (I'm assuming it's Android from the keyboard layout?)
- Which keyboard apps it happens with?

**Comment by JohnAGill** [comment] 2020-09-18 14:57
I've tested this on ios (iphone xr) and can't recreate the issue, looking at the screenshot above it looks like this might be an android only problem

**Comment by floridemai** [comment] 2020-09-23 06:51
Could not reproduce on iOS (XS 13.7) or android (s6 edge, android 7) - see below.

@ahurworth Moving this to blocked. If you can replicate and send more details that would be great.


<img width="720" src="https://user-images.githubusercontent.com/1158133/93976680-ffa78a80-fd81-11ea-98a1-04595645a408.png" />
<img width="720" src="https://user-images.githubusercontent.com/1158133/93976800-37163700-fd82-11ea-9831-ff9c7f2eaba5.png" />

**Comment by AlanSl** [comment] 2020-09-24 12:37
We still can't replicate the issue exactly but on slower Android devices I've found that the appearing keyboard can cause rendering glitches like this one so I've added a small delay before the keyboard is shown. This seems to prevent these glitches.

**Comment by kevin-sheldon** [comment] 2020-10-14 16:26
@ahurworth  I can't seem to repro this. Do we still think this is an issue?

**Comment by AlanSl** [comment] 2020-10-21 15:55
Given the amount of time no-one has been able to reproduce this I'm going to close it, feel free to re-open with details if it or a similar issue show themselves.

**Closed as completed by AlanSl** 2020-10-21 15:55 UTC
Labels: bug
