### ISSUE TITLE
App installed but not registered is not very smooth to start

### ISSUE THREAD

**Issue by denisedresbach** [covid-alert-ny/covid-green-app#601] opened 2020-12-17 20:31 UTC
App version: Android 1.1.1.61 (unable to test on iOS at this time)
OS: Android 11
Device: Pixel 3XL
Reproducible: Always

Summary: Tap link when app is installed, but not registered. First the code screen shows up real quick and then a double load of onboard screen. Once user registers should the code screen show up? User now has to go back and tap link again or find the place to enter the code and enter manually.

Steps:
1. Send a code to your phone where app is installed but not registered
2. Tap link with code in text and open in app

Results: 
1. Screen opens "Share Your Close Contact Codes" with numbers and letters entered and then it disappears
2. Next the Get started screen shows but appears to load up twice
3. Once you go thru the onboarding screens you land on NY Covid Data tab. should it now take user to the share code screen with code entered?

**Comment by AlanSl** [comment] 2020-12-18 16:30
Will be in the build after https://github.com/covid-alert-ny/covid-green-app/pull/603 is merged.

Does both parts:

- **Glitchy re-navigation**: is caused by trying and failing to validate the code while unregistered - I've fixed that.
- **Applying the code after registartion**: The case of a user getting a diagnosis SMS and opening it in the app while unregistered is rare but probably worth handling e.g. if someone primarily uses and has close contacts via the app for, say, NJ; but gets diagnosed via the NYS system. Same PR linked above should make it so that if a user uses a diagnosis link while not registered then registers, it takes them to the upload code screen and enters the code. 

  Note - this flashes the My Covid Alerts screen for a fraction of a second; this is an unavoidable consequence of putting it in the back button history so that when the user goes back after entering the codes they see which tab that feature is under.

**Comment by denisedresbach** [comment] 2020-12-22 19:09
@AlanSl I don't think I have this merge yet. I tested same steps and it seems to be acting the same as it was.
Android build 1.1.1.62

**Comment by AlanSl** [comment] 2021-01-06 13:45
This was merged 4th Jan so should be in build 63 when that goes out.

**Comment by denisedresbach** [comment] 2021-01-06 23:05
I cannot test this until I am able to send links to phone again.

**Comment by denisedresbach** [comment] 2021-01-07 19:17
Verified with 1.1.1.63 - Glitch is resolved and now after onboarding the code is entered. Tested Android only.

**Closed as completed** 2021-01-07 20:17 UTC
Labels: bug
