### ISSUE TITLE
Incorrect calculation of 7 day avg line on the graph

### ISSUE THREAD

**Issue by helloantoine** [covid-alert-ny/covid-green-app#335] opened 2020-09-06 09:01 UTC
![Image from iOS (10)](https://user-images.githubusercontent.com/16833643/92322178-9a386780-f027-11ea-982a-f8ebdd36eff0.png)

Issue: 7 day avg line all flat despite data
Steps: Put Yale as the county. Checkout the second and third graph
Solution: I suspect **No Data** is handled as 0. I think we should ignore these values from the calculation of the mean average.

**Comment by fahd-arshad** [comment] 2020-09-06 20:42
Even if we exclude no data/0, which may or may not be appropriate, this calculation is wrong. There are plenty of positive values over the month, and the 7-day average should show some variation as it hits those positive values.

**Comment by AlanSl** [comment] 2020-09-07 07:36
This is caused by the server calculation for rolling averages rounding the average figure for each day to the nearest integer. 

I had raised this in the original PR adding rolling averages but it looks like it was merged without any changes made: https://github.com/project-vagabond/covid-green-regional-lambdas/pull/16#discussion_r479555053

Example for Tioga:

![Screenshot_20200907-083223_COVID Alert NY](https://user-images.githubusercontent.com/29628323/92360639-12b12e00-f0e5-11ea-92a1-162c5e828f2b.jpg)

**Comment by AlanSl** [comment] 2020-09-07 13:38
@jackmurdoch is on the case, PR https://github.com/project-vagabond/covid-green-regional-lambdas/pull/19 is posted, approved and awaiting deployment.

**Comment by mikegwhit** [comment] 2020-09-08 15:20
We're merged on this.   Should close provided project-vagabond/covid-green-regional-lambdas#19 fixes.

**Comment by floridemai** [comment] 2020-09-09 10:30
I think that PR was merged and changes rolled out to prod as well. Moving to QA for review.

**Comment by fahd-arshad** [comment] 2020-09-10 04:01
Looks good to me now. Next step - break out a pixel ruler and a spreadsheet and calculate the moving averages by hand! 😉

**Closed as completed by fahd-arshad** 2020-09-10 04:01 UTC
Labels: bug, Medium
