### ISSUE TITLE
Close icon requires 2 or 3 taps

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#51] opened 2020-08-24 03:07 UTC
Close icon on top left of most overlays is not usable. Requires many, indeterminate number of taps before it activates. You can see this in "How It Works" and any of the Health Log selectors.

**Comment by davidjharding** [comment] 2020-08-27 14:30
I believe this is related to the fact that the tap target is rather small. This was also flagged in the pre-launch report as an a11y issue.

**Comment by floridemai** [comment] 2020-08-27 15:08
@dharding Could be a duplicate of (related to) https://github.com/project-vagabond/covid-green-app/issues/69.
@fahd-arshad Would you mind checking this one again?

**Comment by fahd-arshad** [comment] 2020-08-28 13:56
It indeed is a duplicate of 69. Will close based on @kevin-sheldon testing that one (can't get to any overlays ATM).

**Closed as completed** 2020-08-28 13:57 UTC
Labels: bug, duplicate
