### ISSUE TITLE
App Crash When Clicking 'My Language'

### ISSUE THREAD

**Issue by rachaelqureshi** [covid-alert-ny/covid-green-app#501] opened 2020-09-22 23:43 UTC
During the SUNY testing, a user indicated that the app was crashing "when clicking on the 'My Language' tab". The user reported using the app in English only. Phone type: Apple SE 2. generation, App Version: 1.0.0.41. 

@kevin-sheldon, please let us know if any other information is needed.

**Comment by JohnAGill** [comment] 2020-09-23 11:45
This has been fixed and will be in the next build

**Comment by AlanSl** [comment] 2020-09-28 10:51
@rachaelqureshi Are you satisfied that the issue is resolved and we can close it? 

We found that a crash as described was occurring on that screen on devices (particularly iOS) where the user's device was only configured to use a language or languages not included in the NYS app (for example, a French device with no other languages configured on the device would default to English but then hit this error on the languages screen only).

The fix to make it safe in such cases went into build 46.

**Comment by rachaelqureshi** [comment] 2020-09-28 12:32
@AlanSl Thank you for looking into this. We can close this issue.

**Closed as completed** 2020-09-28 12:33 UTC
Labels: Critical
